// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"detail":{"path":"detail","id":"detail","parentId":"@@/global-layout","file":"detail.tsx"},"index":{"path":"/","id":"index","parentId":"@@/global-layout","file":"index.tsx"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.tsx","isLayout":true}},
    routeComponents: {
'detail': React.lazy(() => import(/* webpackChunkName: "src__pages__detail" */'../../../src/pages/detail.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
},
  };
}
